// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateSession'](arg1, arg2, arg3);
}

export function GetAllSessions() {
  return window['go']['main']['App']['GetAllSessions']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
